apiVersion: v1
kind: Service
metadata:
  name: mc-app-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    nodeport: 31444
    targetPort: 80
    protocol: TCP
  selector:
    app: mc-app
